// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lingu/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CEFRAdapter());
    registerAdapter(LanguageLocaleAdapter());
    registerAdapter(TopicAdapter());
    registerAdapter(TopicDataAdapter());
    registerAdapter(TopicStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CEFRAdapter());
    registerAdapter(LanguageLocaleAdapter());
    registerAdapter(TopicAdapter());
    registerAdapter(TopicDataAdapter());
    registerAdapter(TopicStatusAdapter());
  }
}
